#
# Test YAML config
#

# 主节点
type: test
sn: 12345678901234567890
# etcd : http://192.168.1.173:8379

# 子节点

host:
  ip: 127.0.0.1
  port:
    http: 8000
    rtsp: 554
    sip: 5060

# 数组
servers:
  - cms
  - vms
  - ops
  - ms

clients:
  -
    name: 1
    enable: true
  -
    name: 2
    enable: false
  -
    name: 3
    enable: true
    
debug: false