# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: nothingdocker/centos-dev:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
#services:
#  - mongo:latest
#  - redis:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

stages:
  - test
  - deploy

before_script:
  - echo 'REDIS_HOST=redis' >> .env
  - echo 'DB_HOST=mongo' >> .env
  - npm install

test_service:
  stage: test
  script:
    - npm test
  only:
    - master

deploy:
  stage: deploy
  script:
    - echo 'deploy success'
  only:
    - master

